apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: d8zybglls-go 
  janus-idp.io/tekton: d8zybglls-go
  backstage.io/kubernetes-id: d8zybglls-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: d8zybglls-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml